Golden Ratio code but there's something wrong with it. At least we have a goden rat though, that's pretty cool though

In [1]:
import numpy as np

def potential(r, sigma = 1, V0 = 1):
    return V0 * ((sigma/r)**6 - np.exp(-r/sigma) )

def goldRat(x1,x4, accurate_power, printing= True):
    z = (1 + np.sqrt(5)) / 2 # The Gold Rat
    x2 = x4 - (x4-x1)/z
    x3 = x1 + (x4-x1)/z
    
    accurate = 10**(-1 *accurate_power)
    cond1 = x4 - x1


    while cond1 > accurate:

        if potential(x2) < potential(x3):
            x4 = x3
            x3 = x2
            x2 = x4 - (x4 -x1)/z
            print( " x2 < x3 " )
            print(x2, x3, x4)
        else:
            x1 = x2
            x2 = x3
            x3 = x1 - (x4-x1)/z
        cond1 = x4 - x1
        
    return (x1+x4)/2
        
goldRat(0,8,3)

 x2 < x3 
1.8885438199983176 3.0557280900008417 4.944271909999158
 x2 < x3 
1.167184270002524 1.8885438199983176 3.0557280900008417
 x2 < x3 
0.7213595499957941 1.8885438199983176 2.220446049250313e-16


0.5835921350012621

Gradient Descent

In [2]:
def grad_descent(function, start, step , accuracy):
    accuracy = 10**(-1*accuracy)
    deriv = (function(start+step) - function(start)) / step # Basic Euler's for derivative
    newplace = start - deriv
    
    cond1 = np.abs(newplace - start)
    terminator = 1
    while cond1 > accuracy:
        deriv = (function(start+step) - function(start)) / step # Basic Euler's for derivative
        newplace = start - deriv
        cond1 = np.abs(newplace - start)
        start = newplace
        terminator +=1
        if terminator > 10000:
            break
    return newplace
        

grad_descent(potential,4, .001,5)

1.6300201205024551

In [3]:
def grad_NDescent(function, start,step,accuracy):
    accuracy = 10**(-1*accuracy)
    deriv = np.zeros_like(start,float)
    for i in range(0,len(start)):
        nderiv = (function(start[i]+step) - function(start[i])) / step
        deriv[i] = nderiv

    newplace = start - deriv
    cond1 = np.abs(np.sum(newplace))
    start = newplace
    terminator = 1
    while cond1 > accuracy:
        for i in range(0,len(start)):
            nderiv = (function(start[i]+step) - function(start[i])) / step
            deriv[i] = nderiv
        newplace = start - deriv
        cond1 = np.abs(np.sum(newplace))
        start = newplace
        terminator += 1
        
        if terminator > 10000:
            break
    return newplace


Newton's Descent Method I guess

In [4]:
def new_descent(function,x1,x2,gamma,accuracy):
    accuracy = 10**(-1*accuracy)
    x3 = x2 - gamma* (function(x2) - function(x1)) / (x2-x1)
    cond1 = np.abs(x3-x2)
    x1 = x2
    x2 = x3
    terminator = 1
    while cond1 > accuracy:
        x3 = x2 - gamma* (function(x2) - function(x1)) / (x2-x1)
        cond1 = np.abs(x3-x2)
        x1 = x2
        x2 = x3
        terminator +=1
        if terminator > 10000:
            break
    return x3

new_descent(potential,1,3,1,4)

1.6303667604075642

Just messing around with np.meshgrid; not relevant to above

In [13]:
x = y = np.arange(0,10,1)
X,Y = np.meshgrid(x,y)

print("X")
print(X)
print("Y")
print(Y)
print("X*Y")
print(X*Y)

X
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
Y
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]
X*Y
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
